---
# single_host_ping.yml - 針對單一主機的簡單 Ping playbook
# 使用方式: ansible-playbook -i inventory_file single_host_ping.yml

- name: Ping a single host
  hosts: target_host  # 在inventory中定義的主機或組名
  gather_facts: no
  
  tasks:
    - name: Ping test
      ansible.builtin.ping:
      register: ping_result
      
    - name: Display ping status
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is REACHABLE"
      when: ping_result is success
      
    - name: Show failure message if ping fails
      ansible.builtin.debug:
        msg: "WARNING: Host {{ inventory_hostname }} is UNREACHABLE!"
      when: ping_result is failed
      
    - name: Show connection details
      ansible.builtin.debug:
        msg: "Connection details - Host: {{ inventory_hostname }}, IP: {{ ansible_host | default('Not Specified') }}"
